import { AuditLog } from './types';

export const mockAuditLogs: AuditLog[] = [
  {
    audit_id: 1,
    table_name: 'companies',
    record_id: 123,
    operation: 'UPDATE',
    performed_by: 'john.doe@example.com',
    performed_at: '2024-03-14T15:30:00Z',
    ip_address: '192.168.1.100',
    user_agent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/120.0.0.0',
    status: 'success',
    severity: 'low',
    details: 'Company details updated',
    changes: [
      {
        audit_change_id: 1,
        column_name: 'company_name',
        old_value: 'TechCorp',
        new_value: 'TechCorp Solutions',
      },
      {
        audit_change_id: 2,
        column_name: 'status',
        old_value: 'active',
        new_value: 'inactive',
      },
    ],
  },
  {
    audit_id: 2,
    table_name: 'users',
    record_id: 456,
    operation: 'INSERT',
    performed_by: 'admin@example.com',
    performed_at: '2024-03-14T15:15:00Z',
    ip_address: '192.168.1.101',
    user_agent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) Safari/605.1.15',
    status: 'success',
    severity: 'medium',
    details: 'New user created',
  },
  {
    audit_id: 3,
    table_name: 'sessions',
    record_id: 789,
    operation: 'DELETE',
    performed_by: 'system@example.com',
    performed_at: '2024-03-14T15:00:00Z',
    ip_address: '192.168.1.102',
    user_agent: 'System Cleanup Service',
    status: 'success',
    severity: 'low',
    details: 'Expired session removed',
  },
  {
    audit_id: 4,
    table_name: 'companies',
    record_id: 234,
    operation: 'UPDATE',
    performed_by: 'jane.smith@example.com',
    performed_at: '2024-03-14T14:45:00Z',
    ip_address: '192.168.1.103',
    user_agent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) Firefox/123.0',
    status: 'warning',
    severity: 'medium',
    details: 'Partial update completed',
  },
  {
    audit_id: 5,
    table_name: 'users',
    record_id: 567,
    operation: 'DELETE',
    performed_by: 'admin@example.com',
    performed_at: '2024-03-14T14:30:00Z',
    ip_address: '192.168.1.104',
    user_agent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) Edge/120.0.0.0',
    status: 'error',
    severity: 'high',
    details: 'User deletion failed - foreign key constraint',
  },
  {
    audit_id: 6,
    table_name: 'products',
    record_id: 890,
    operation: 'INSERT',
    performed_by: 'sarah.jones@example.com',
    performed_at: '2024-03-14T14:15:00Z',
    ip_address: '192.168.1.105',
    user_agent: 'Mozilla/5.0 (iPhone; CPU iPhone OS 17_3_1 like Mac OS X) Version/17.2 Mobile/15E148 Safari/604.1',
    status: 'success',
    severity: 'low',
    details: 'New product added',
  },
  {
    audit_id: 7,
    table_name: 'orders',
    record_id: 345,
    operation: 'UPDATE',
    performed_by: 'system@example.com',
    performed_at: '2024-03-14T14:00:00Z',
    ip_address: '192.168.1.106',
    user_agent: 'Order Processing Service',
    status: 'warning',
    severity: 'high',
    details: 'Order status update timeout',
  },
  {
    audit_id: 8,
    table_name: 'payments',
    record_id: 678,
    operation: 'INSERT',
    performed_by: 'payment.service@example.com',
    performed_at: '2024-03-14T13:45:00Z',
    ip_address: '192.168.1.107',
    user_agent: 'Payment Processing Service',
    status: 'error',
    severity: 'high',
    details: 'Payment processing failed',
  },
  {
    audit_id: 9,
    table_name: 'inventory',
    record_id: 901,
    operation: 'UPDATE',
    performed_by: 'warehouse@example.com',
    performed_at: '2024-03-14T13:30:00Z',
    ip_address: '192.168.1.108',
    user_agent: 'Inventory Management System',
    status: 'success',
    severity: 'medium',
    details: 'Stock levels updated',
  },
  {
    audit_id: 10,
    table_name: 'customers',
    record_id: 456,
    operation: 'UPDATE',
    performed_by: 'support@example.com',
    performed_at: '2024-03-14T13:15:00Z',
    ip_address: '192.168.1.109',
    user_agent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/120.0.0.0',
    status: 'success',
    severity: 'low',
    details: 'Customer details updated',
  },
  {
    audit_id: 11,
    table_name: 'marketing',
    record_id: 789,
    operation: 'INSERT',
    performed_by: 'marketing@example.com',
    performed_at: '2024-03-14T13:00:00Z',
    ip_address: '192.168.1.110',
    user_agent: 'Campaign Management Tool',
    status: 'success',
    severity: 'low',
    details: 'New campaign created',
  },
  {
    audit_id: 12,
    table_name: 'employees',
    record_id: 234,
    operation: 'DELETE',
    performed_by: 'hr@example.com',
    performed_at: '2024-03-14T12:45:00Z',
    ip_address: '192.168.1.111',
    user_agent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) Chrome/120.0.0.0',
    status: 'warning',
    severity: 'high',
    details: 'Employee record archived',
  },
  {
    audit_id: 13,
    table_name: 'permissions',
    record_id: 567,
    operation: 'UPDATE',
    performed_by: 'security@example.com',
    performed_at: '2024-03-14T12:30:00Z',
    ip_address: '192.168.1.112',
    user_agent: 'Access Control System',
    status: 'success',
    severity: 'high',
    details: 'Permission levels modified',
  },
  {
    audit_id: 14,
    table_name: 'configurations',
    record_id: 890,
    operation: 'UPDATE',
    performed_by: 'system@example.com',
    performed_at: '2024-03-14T12:15:00Z',
    ip_address: '192.168.1.113',
    user_agent: 'System Configuration Service',
    status: 'error',
    severity: 'high',
    details: 'Configuration update failed',
  },
  {
    audit_id: 15,
    table_name: 'backups',
    record_id: 345,
    operation: 'INSERT',
    performed_by: 'backup.service@example.com',
    performed_at: '2024-03-14T12:00:00Z',
    ip_address: '192.168.1.114',
    user_agent: 'Automated Backup System',
    status: 'success',
    severity: 'medium',
    details: 'Scheduled backup completed',
  }
];

export const filterOptions = [
  { value: 'all', label: 'All Operations' },
  { value: 'insert', label: 'Inserts' },
  { value: 'update', label: 'Updates' },
  { value: 'delete', label: 'Deletes' },
];
