package ai.yuvi.model;

public enum Industry {
    TECHNOLOGY,
    HEALTHCARE,
    FINANCE,
    RETAIL,
    MANUFACTURING,
    EDUCATION,
    ENTERTAINMENT,
    AUTOMOTIVE,
    ENERGY,
    REAL_ESTATE,
    TELECOMMUNICATIONS,
    TRANSPORTATION,
    AGRICULTURE,
    CONSTRUCTION,
    HOSPITALITY,
    MEDIA,
    PROFESSIONAL_SERVICES,
    OTHER
} 