import { Company } from './types';

export const mockCompanies: Company[] = [
  {
    id: 1,
    name: 'TechCorp Solutions',
    industry: 'Technology',
    status: 'active',
    employees: 1250,
    applications: 5,
    lastActive: '2024-03-14 09:45 AM',
  },
  {
    id: 2,
    name: 'Global Finance Inc',
    industry: 'Finance',
    status: 'active',
    employees: 3420,
    applications: 8,
    lastActive: '2024-03-14 10:30 AM',
  },
  {
    id: 3,
    name: 'HealthCare Plus',
    industry: 'Healthcare',
    status: 'inactive',
    employees: 890,
    applications: 2,
    lastActive: '2024-03-13 03:15 PM',
  },
  {
    id: 4,
    name: 'Retail Masters',
    industry: 'Retail',
    status: 'active',
    employees: 2150,
    applications: 4,
    lastActive: '2024-03-14 11:20 AM',
  },
  {
    id: 5,
    name: 'EduTech Systems',
    industry: 'Education',
    status: 'pending',
    employees: 450,
    applications: 1,
    lastActive: '2024-03-14 08:00 AM',
  },
  {
    id: 6,
    name: 'Manufacturing Pro',
    industry: 'Manufacturing',
    status: 'active',
    employees: 1780,
    applications: 6,
    lastActive: '2024-03-14 09:00 AM',
  },
  {
    id: 7,
    name: 'Energy Solutions',
    industry: 'Energy',
    status: 'active',
    employees: 920,
    applications: 3,
    lastActive: '2024-03-14 10:45 AM',
  },
  {
    id: 8,
    name: 'Logistics Hub',
    industry: 'Transportation',
    status: 'inactive',
    employees: 670,
    applications: 2,
    lastActive: '2024-03-13 04:30 PM',
  },
];
